---

# ansible-playbook -i ../../vagrant-ansible-common/XXX/hosts ossecelk.yml -v

#########################
# CIS Hardening         #
#########################

- hosts: ossecservers
  sudo: true
  tags: cis
  roles:
    - role: ansible-cis
    
#########################
# Elasticsearch install #
#########################

- hosts: ossecservers
  sudo: true
  tags: elasticsearch
  roles:
    - ansible-elasticsearch

#########################
# Logstash install #
#########################

- hosts: ossecservers
  sudo: true
  tags: logstash
  roles:
    - ansible-logstash

#########################
# Kibana install #
#########################

- hosts: ossecservers
  sudo: true
  tags: kibana
  roles:
   - ansible-kibana

#########################
# Nginx reverse proxy   #
#########################

- hosts: ossecservers
  sudo: true
  tags: nginx
  roles:
    - ansible-nginx
    
#########################
# Ossec install #
#########################

- hosts: ossecservers
  sudo: true
  tags: ossec
  roles:
    - ansible-ossec
    