---
# The user to run nginx
nginx_user: "www-data"

nginx_hhvm: |
      add_header X-backend hhvm;
      try_files $uri $uri/ /index.php?$args;
      location ~ \.(hh|php)$ {
        try_files     $uri =404;
        fastcgi_pass  unix:/var/run/hhvm/sock;
        fastcgi_index index.php;
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;
        include       fastcgi_params;
      }

# A list of directives for the events section.
nginx_events_params:
  - worker_connections 512

# A list of hashs that define the servers for nginx,
# as with http parameters. Any valid server parameters
# can be defined here.
nginx_http_params:
  - sendfile on
  - access_log /var/log/nginx/access.log

nginx_sites:
 default:
     - listen 443
     - server_name {{ hugin_hostname }}
     
     - ssl on
     - ssl_certificate /etc/pki/tls/server.crt
     - ssl_certificate_key /etc/pki/tls/server.key

     - keepalive_timeout    60
     - ssl_session_cache    shared:SSL:10m
     - ssl_session_timeout 10m
     
     - ssl_protocols TLSv1.2
     - ssl_ciphers "HIGH:!aNULL:!MD5 or HIGH:!aNULL:!MD5:!3DES"
     - ssl_prefer_server_ciphers on
     - location / { auth_pam "Secure Zone"; auth_pam_service_name "nginx"; proxy_pass http://kibana; }

# A list of hashs that define additional configuration
nginx_configs:
  proxy:
      - proxy_set_header X-Real-IP  $remote_addr
      - proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for
      - proxy_redirect off
      - proxy_http_version 1.1
      - proxy_set_header Connection ""

      - proxy_set_header  Host $http_host
      - proxy_set_header  Accept-Encoding   ""
      - proxy_set_header  X-Forwarded-Proto $scheme

      # For CORS Ajax
      - proxy_pass_header Access-Control-Allow-Origin
      - proxy_pass_header Access-Control-Allow-Methods
      - proxy_hide_header Access-Control-Allow-Headers
      - add_header Front-End-Https   on
      - add_header Access-Control-Allow-Headers 'X-Requested-With, Content-Type'
      - add_header Access-Control-Allow-Credentials true

      - proxy_headers_hash_max_size 51200
      - proxy_headers_hash_bucket_size 6400
  upstream:
      - upstream kibana {
          server 127.0.0.1:5601;   
          keepalive 64;
        }

  geo:
      - geo $local {
          default 0;
          127.0.0.1 1;
        }
  gzip:
      - gzip on
      - gzip_disable msie6
